# Generated by cucumber-sinatra. (2013-09-27 12:32:01 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/chitter')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'capybara/rspec'

Capybara.app = Chitter

class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ChitterWorld.new
end
